spring:
  application:
    name: security-demo
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://114.115.175.72:3306/task_db?characterEncoding=utf8&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
  session:
    store-type: none
  security:
    user:
      name: admin
      password: admin
#返回时间转换为毫秒
  jackson:
    serialization: 
      write-dates-as-timestamps: true